[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -c tailwind/tailwind.config.js -i tailwind/src/input.css -o static/css/blog.css"]